[package]
name = "blackjack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
terminal-menu = "2.0.4"
crossterm = "0.23.2"

[build-dependencies]
winres = "0.1.12"
